### ISSUE TITLE
Webhooks on push to branches

### ISSUE THREAD

**Issue by TRICOT-Hugo** [alexarne/DD2480-CI#1]
The GitHub repository must send an HTTP request to the CI server when a push has been commited to a branch, and the said branch must be part of the info in the HTTP request.

**Comment by haaker1** [comment]
How to create: https://docs.github.com/en/webhooks/using-webhooks/creating-webhooks
WHat the payload contains: https://docs.github.com/en/webhooks/webhook-events-and-payloads

**Comment by alexarne** [comment]
Not relevant anymore. Re-configure webhook upon each CI reboot.
